name: Create a tag any time package.json's version changes
on:
  push:
    branches:
      - develop
    paths:
      - package.json
jobs:
  tag-npm-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV
      - name: Create tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
